export type PatentSubsystem = 'source' | 'collector' | 'illumination' | 'reticle' | 'projection' | 'stage' | 'metrology' | 'vacuum'

export type PatentRecord = {
  id: string
  familyId: string
  familyLabel: string
  familyMembers: string[]
  title: string
  priorityDate: string
  publicationDate: string
  subsystem: PatentSubsystem
  linkedSubsystems: PatentSubsystem[]
  assignee: string
  applicationNumber?: string
  summary: string
  url: string
  confidence: 'patent'
}

export const patents: PatentRecord[] = [
  {
    id: 'EP4239410A1',
    familyId: 'RETICLE-SHIELD-2022',
    familyLabel: 'Reflective-reticle shielding family',
    familyMembers: ['EP4239410A1', 'WO2023165837A1', 'KR20240154554A'],
    title: 'Reticle stage',
    priorityDate: '2022-03-01',
    publicationDate: '2023-09-06',
    subsystem: 'reticle',
    linkedSubsystems: ['reticle', 'stage'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'EP22159521.8A',
    summary: 'Published EUV reticle-stage disclosure describing support for a reflective reticle and configurable shielding elements.',
    url: 'https://patents.google.com/patent/EP4239410A1/en',
    confidence: 'patent',
  },
  {
    id: 'US20250328068A1',
    familyId: 'REFLECTIVE-MEMBER-2022',
    familyLabel: 'Reflective-member EUV family',
    familyMembers: ['WO2024027999A1', 'US20250328068A1', 'KR20250044824A', 'JP2025523751A', 'CN119522403A', 'TW202414071A'],
    title: 'Reflective member for EUV lithography',
    priorityDate: '2022-07-30',
    publicationDate: '2025-10-23',
    subsystem: 'projection',
    linkedSubsystems: ['illumination', 'reticle', 'projection'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'US18/868,388',
    summary: 'Public disclosure covering reflective members, an EUV mask and a lithographic apparatus with illuminator, reticle support, wafer table and reflective projection system.',
    url: 'https://patents.google.com/patent/US20250328068A1/en',
    confidence: 'patent',
  },
  {
    id: 'US20240103387A1',
    familyId: 'SOURCE-CONTAMINATION-2018',
    familyLabel: 'Source-contamination mitigation family',
    familyMembers: ['US20240103387A1'],
    title: 'Reducing contamination from source material in an EUV light source',
    priorityDate: '2018-10-22',
    publicationDate: '2024-03-28',
    subsystem: 'source',
    linkedSubsystems: ['source', 'collector', 'vacuum'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'US18/528,933',
    summary: 'Public source-module disclosure focused on contamination generated by plasma target material and mitigation around EUV collection optics.',
    url: 'https://patents.google.com/patent/US20240103387A1/en',
    confidence: 'patent',
  },
  {
    id: 'US8598551B2',
    familyId: 'DROPLET-ACCELERATOR-2010',
    familyLabel: 'Droplet-accelerator source family',
    familyMembers: ['US20120280149A1', 'US8598551B2'],
    title: 'EUV radiation source comprising a droplet accelerator',
    priorityDate: '2010-01-07',
    publicationDate: '2013-12-03',
    subsystem: 'source',
    linkedSubsystems: ['source', 'collector'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'US13/520,993',
    summary: 'Published EUV source disclosure involving target droplets, a droplet accelerator, laser irradiation and a source-collector module.',
    url: 'https://patents.google.com/patent/US8598551B2/en',
    confidence: 'patent',
  },
  {
    id: 'US20230164900A1',
    familyId: 'DROPLET-GAS-ACCELERATION-2020',
    familyLabel: 'Droplet gas-acceleration family',
    familyMembers: ['US20230164900A1'],
    title: 'Accelerating droplets in a droplet generator for an EUV source',
    priorityDate: '2020-06-29',
    publicationDate: '2023-05-25',
    subsystem: 'source',
    linkedSubsystems: ['source'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'US18/011,593',
    summary: 'Public patent-family member describing a droplet coalescence zone and gas acceleration zone within an EUV target-material generator.',
    url: 'https://patents.google.com/patent/US20230164900A1/en',
    confidence: 'patent',
  },
  {
    id: 'EP1107068A2',
    familyId: 'REFLECTOR-POSITIONING-1999',
    familyLabel: 'Reflector-positioning family',
    familyMembers: ['EP1107068A2', 'EP1107068A3', 'EP1107068B1'],
    title: 'Lithographic projection apparatus with system for positioning a reflector',
    priorityDate: '1999-11-30',
    publicationDate: '2001-06-13',
    subsystem: 'stage',
    linkedSubsystems: ['projection', 'stage', 'metrology'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'EP00310370A',
    summary: 'Early public disclosure around sensing and precise positioning of a reflector in lithographic projection equipment.',
    url: 'https://patents.google.com/patent/EP1107068A2/en',
    confidence: 'patent',
  },
  {
    id: 'EP4045949A1',
    familyId: 'COLLECTOR-PUMP-GRATING-2019',
    familyLabel: 'Collector mirror pump-light grating family',
    familyMembers: ['EP4045949A1', 'EP4045949B1'],
    title: 'EUV collector mirror',
    priorityDate: '2019-10-15',
    publicationDate: '2022-08-24',
    subsystem: 'collector',
    linkedSubsystems: ['source', 'collector'],
    assignee: 'Carl Zeiss SMT GmbH / ASML Netherlands B.V.',
    summary: 'Public disclosure for an EUV collector mirror with a reflecting surface and a pump-light grating concept intended to return pump light toward the source region.',
    url: 'https://patents.google.com/patent/EP4045949A1/en',
    confidence: 'patent',
  },
  {
    id: 'EP1109067B1',
    familyId: 'ILLUMINATOR-INTENSITY-1999',
    familyLabel: 'Illumination intensity-control family',
    familyMembers: ['EP1109067A2', 'EP1109067A3', 'EP1109067B1'],
    title: 'Illuminator',
    priorityDate: '1999-12-13',
    publicationDate: '2006-05-24',
    subsystem: 'illumination',
    linkedSubsystems: ['illumination', 'projection'],
    assignee: 'ASML Netherlands B.V.',
    applicationNumber: 'EP20000311007',
    summary: 'Public illumination-system disclosure describing control of radiation intensity distribution at a plane in a lithographic apparatus.',
    url: 'https://patents.google.com/patent/EP1109067B1/en',
    confidence: 'patent',
  },
  {
    id: 'EP3977207A1',
    familyId: 'ELECTROSTATIC-CLAMP-2019',
    familyLabel: 'Split double-sided wafer and reticle clamp family',
    familyMembers: ['EP3977207A1'],
    title: 'Split double sided wafer and reticle clamps',
    priorityDate: '2019-05-29',
    publicationDate: '2022-04-06',
    subsystem: 'stage',
    linkedSubsystems: ['reticle', 'stage', 'vacuum'],
    assignee: 'ASML Holding N.V.',
    summary: 'Public disclosure describing electrostatic clamp concepts for supporting a reticle or substrate in a vacuum system such as an EUV lithography system.',
    url: 'https://patents.google.com/patent/EP3977207A1/en',
    confidence: 'patent',
  },
  {
    id: 'WO2017186486A1',
    familyId: 'EUV-MEMBRANE-2016',
    familyLabel: 'EUV membrane / pellicle family',
    familyMembers: ['WO2017186486A1', 'US10908496B2', 'EP4202545A1'],
    title: 'A membrane for EUV lithography',
    priorityDate: '2016-04-25',
    publicationDate: '2017-11-02',
    subsystem: 'reticle',
    linkedSubsystems: ['reticle'],
    assignee: 'ASML Netherlands B.V.',
    summary: 'Public EUV-lithography disclosure for a membrane concept associated with the mask/reticle environment and later family members.',
    url: 'https://patents.google.com/patent/WO2017186486A1/en',
    confidence: 'patent',
  },
]

export const patentFamilies = Array.from(new Map(patents.map((patent) => [patent.familyId, {
  id: patent.familyId,
  label: patent.familyLabel,
  priorityDate: patent.priorityDate,
  members: patent.familyMembers,
  subsystems: Array.from(new Set(patents.filter((candidate) => candidate.familyId === patent.familyId).flatMap((candidate) => candidate.linkedSubsystems))),
}])).values()).sort((a, b) => a.priorityDate.localeCompare(b.priorityDate))

export const patentSubsystems: Array<{ id: 'all' | PatentSubsystem; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'source', label: 'Source' },
  { id: 'collector', label: 'Collector' },
  { id: 'illumination', label: 'Illumination' },
  { id: 'reticle', label: 'Reticle' },
  { id: 'projection', label: 'Projection' },
  { id: 'stage', label: 'Wafer / reticle stage' },
  { id: 'metrology', label: 'Metrology' },
  { id: 'vacuum', label: 'Vacuum' },
]

export const patentCoverage = patentSubsystems.filter((item): item is { id: PatentSubsystem; label: string } => item.id !== 'all').map((item) => ({
  id: item.id,
  label: item.label,
  count: patents.filter((patent) => patent.linkedSubsystems.includes(item.id)).length,
}))
