export type PatentSubsystem = 'source' | 'reticle' | 'projection' | 'stage' | 'metrology'

export type PatentRecord = {
  id: string
  title: string
  publicationYear: number
  subsystem: PatentSubsystem
  assignee: string
  summary: string
  url: string
  confidence: 'patent'
}

export const patents: PatentRecord[] = [
  {
    id: 'EP4239410A1',
    title: 'Reticle stage',
    publicationYear: 2023,
    subsystem: 'reticle',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Published EUV reticle-stage disclosure describing support for a reflective reticle and configurable shielding elements.',
    url: 'https://patents.google.com/patent/EP4239410A1/en',
    confidence: 'patent',
  },
  {
    id: 'US20250328068A1',
    title: 'Reflective member for EUV lithography',
    publicationYear: 2025,
    subsystem: 'projection',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Public disclosure covering reflective members, an EUV mask and a lithographic apparatus with illuminator, reticle support, wafer table and reflective projection system.',
    url: 'https://patents.google.com/patent/US20250328068A1/en',
    confidence: 'patent',
  },
  {
    id: 'US20240103387A1',
    title: 'Reducing contamination from source material in an EUV light source',
    publicationYear: 2024,
    subsystem: 'source',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Public source-module disclosure focused on contamination generated by plasma target material and mitigation around EUV collection optics.',
    url: 'https://patents.google.com/patent/US20240103387A1/en',
    confidence: 'patent',
  },
  {
    id: 'US8598551B2',
    title: 'EUV radiation source comprising a droplet accelerator',
    publicationYear: 2013,
    subsystem: 'source',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Published EUV source disclosure involving target droplets and an accelerator in a lithographic apparatus.',
    url: 'https://patents.google.com/patent/US8598551B2/en',
    confidence: 'patent',
  },
  {
    id: 'US20230164900A1',
    title: 'Accelerating droplets in a droplet generator for an EUV source',
    publicationYear: 2023,
    subsystem: 'source',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Public patent-family member describing droplet acceleration within an EUV target-material generator.',
    url: 'https://patents.google.com/patent/US20230164900A1/en',
    confidence: 'patent',
  },
  {
    id: 'EP1107068A2',
    title: 'Lithographic projection apparatus with system for positioning a reflector',
    publicationYear: 2001,
    subsystem: 'stage',
    assignee: 'ASML Netherlands B.V.',
    summary: 'Early public disclosure around precise positioning of a reflector in lithographic projection equipment.',
    url: 'https://patents.google.com/patent/EP1107068A2/en',
    confidence: 'patent',
  },
]

export const patentSubsystems: Array<{ id: 'all' | PatentSubsystem; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'source', label: 'Source' },
  { id: 'reticle', label: 'Reticle' },
  { id: 'projection', label: 'Projection' },
  { id: 'stage', label: 'Stage' },
  { id: 'metrology', label: 'Metrology' },
]
